### ISSUE TITLE
Support for Gatsby V2

### ISSUE THREAD

**Issue by ThePaulMcBride** [escaladesports/gatsby-plugin-markdown-pages#1]
I'm not sure if there is something unusual with my build, but I can't seem to get this working. As soon as I include the package I get the following error.

`GraphQLError: Cannot query field "fields" on type "MarkdownRemark"`

I'm fairly inexperienced with Gatsby, but I'd love to get to the bottom of this.

**Comment by tbaustin** [comment]
Can you provide repo?

**Comment by ThePaulMcBride** [comment]
Sure!

https://github.com/ThePaulMcBride/paulmcbride.net/tree/feature/gatsby-rewrite

**Comment by ThePaulMcBride** [comment]
Okay, with a few tweaks, this has helped massively!

However, I have no idea how to access the data from that page in my template. None of the data in the markdown file is passed to the template as props.

Am I doing something wrong?

**Comment by tbaustin** [comment]
Is any of the markdown passing through ? For example is the `About us copy...` coming through to the template.

**Comment by ThePaulMcBride** [comment]
Unfortunately not. I can't find the content or the data in the frontmatter in the props passed to the template.

**Comment by kennedyrose** [comment]
The data will still have to be queried through GraphQL just as you would markdown data. Do you have a query in your template component?

**Comment by ThePaulMcBride** [comment]
I have not! I know how to add a query, but how would I go about getting the data from the related markdown file?

**Comment by tbaustin** [comment]
@ThePaulMcBride  you could query by the id or path.

```
markdownRemark(frontmatter: {id: {eq: "mypage"} } ){
  frontmatter {
   id
   title 
 }
}
```

Let me know if that helps!

**Comment by ThePaulMcBride** [comment]
Sorry, for not replying sooner, I just didn't know what I was doing. You're right, if I query the data correctly it works. Thanks for the support!
